### ISSUE TITLE
Upgrade raven deps

### ISSUE THREAD

**Issue by j1348** [jsynowiec/good-sentry#1]
I think you can upgrade the [raven](https://github.com/getsentry/raven-node) dependency, as now it is in `1.x.x`.

**Comment by jsynowiec** [comment]
Thanks for the notice. Already updated, please see the https://github.com/jsynowiec/good-sentry/commit/0a4319a055256995c84ef3a0c7926f038effeffe commit. It's available in the 1.0.0 release.
Can you confirm if it works correctly?

**Comment by j1348** [comment]
maybe the `1.1.1` seems to be the last one.
https://github.com/getsentry/raven-node
