### ISSUE TITLE
Warning when using the patchGlobal with the raven v1.1.1

### ISSUE THREAD

**Issue by j1348** [jsynowiec/good-sentry#2]
I getting this warning when using the `patchGlobal` set to true.

```raven@1.1.1 alert: patchGlobal has been deprecated and will be removed in v2.0; use install instead.```

**Comment by jsynowiec** [comment]
As of `raven@1.0.0`, `new raven.Client` and `patchGlobal` are depreciated. 

Ref: https://github.com/getsentry/raven-node/blob/master/History.md#100---12122016

**Comment by jsynowiec** [comment]
This is only a depreciation warning but everything works.

**Comment by j1348** [comment]
You update the docs, so now there are no references to `patchGlobal`.

**Comment by jsynowiec** [comment]
This is now resolved in the [1.0.3](https://github.com/jsynowiec/good-sentry/releases/tag/1.0.3) release. If you want to capture all uncaught errors, please use the `captureUncaught: true` option of the `GoodSentry` constructor, as described in the [README](https://github.com/jsynowiec/good-sentry#new-goodsentry-options).

**Comment by j1348** [comment]
I notice this. Thank you for your quick answer.
